name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access the EC2 instance
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      # Step 3: Run commands on EC2 to handle the app
      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.226.131.47 "
            # Check if the app is already running on port 3000 and kill it if necessary
            if lsof -i :3000; then
              echo 'Application is already running on port 3000, stopping it...'
              pid=\$(lsof -t -i :3000)
              kill -9 \${pid}
              # Wait a bit to ensure the process is killed
              sleep 5
            fi
            # Check again if the process is killed
            if lsof -i :3000; then
              echo 'Failed to stop the existing process on port 3000'
              exit 1
            fi
            # Now, run the Node.js app
            nohup node /home/ubuntu/new/nodejsapp/app.js &"
