name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      
      - name: Run Ansible playbook on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.226.131.47> << 'EOF'
            cd /home/ubuntu
            ansible-playbook -i hosts.ini nodeapp.yml  
          EOF
