name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access the EC2 instance
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      # Step 3: Run Ansible playbook on EC2 (without heredoc)
      - name: Run Ansible playbook on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.226.131.47 "
            # Check if Node.js is already running on port 3000
            if ! lsof -i :3000; then
              echo 'Application is not running. Starting the application...';
              nohup node /home/ubuntu/new/nodejsapp/app.js &
            else
              echo 'Application is already running on port 3000';
            fi
            cd /home/ubuntu && ansible-playbook -i hosts.ini nodeapp.yml
          "
