name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access the EC2 instance
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      # Step 3: Run Ansible playbook on EC2
      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.226.131.47 "
            # Run the Ansible playbook to manage the Node.js application
            echo 'Running Ansible playbook to deploy the Node.js application...'
            cd /home/ubuntu && ansible-playbook -i hosts.ini nodeapp.yml
          "
