---
- name: Deploy Node.js App to EC2
  hosts: all
  become: yes
  tasks:

    - name: Check if the Node.js application is running
      command: lsof -i :3000
      register: app_running
      ignore_errors: true

    - name: Start Node.js app if not running
      shell: nohup node /home/ubuntu/new/nodejsapp/app.js &
      when: app_running.rc != 0
      ignore_errors: true
      async: 0
      poll: 0
      become: yes
