name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access the EC2 instance
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      # Step 3: Run Ansible playbook on EC2
      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.226.131.47 "
            # Check if Node.js is already running on port 3000
            pid=\$(lsof -t -i :3000)
            if [ -n \"\$pid\" ]; then
              echo 'Node.js app is already running. Stopping it...';
              # Kill the process occupying port 3000
              kill -9 \$pid;
            else
              echo 'No application is running on port 3000';
            fi

            # Run the Ansible playbook to deploy and start the Node.js app
            cd /home/ubuntu && ansible-playbook -i hosts.ini nodeapp.yml
          "
