name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2 with Ansible
      - name: Deploy to EC2 with Ansible
        run: |
          sudo apt update && sudo apt install -y ansible
          echo "[nodeapp]" > inventory.ini
          echo "54.226.11.47  ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa" >> inventory.ini
          ansible-playbook -i inventory.ini nodejsapp.yml
